### ISSUE TITLE
PayHost Support

### ISSUE THREAD

**Issue by sitatec** [distributhor/paygate-sdk#6]
Hi @distributhor,
Does this sdk support [PayHost (host-to-host)](https://docs.paygate.co.za/#payhost) ?

**Comment by distributhor** [comment]
Hi. Currently it does not support PayHost. I am not too familiar with it, but can have a look at what PayHost is, and see if perhaps it's possible and feasible..

**Comment by distributhor** [comment]
I've read up a bit on PayHost. It seems more suited to a typical enterprise environment (not strictly 'end user' e-commerce per se), and integration with PayHost will probably be easier using a language that has strong SOAP supports, such as Java. It's not impossible to build such support into this JS client, but would require some effort, and the possible use cases for it (in a typical JS app context) might not be big enough to justify such a development effort. 

Are you perhaps able to provide a use case or two for how it might be used?
